{{ range .Values.functions }}
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: {{ .name }}
spec:
  ignoreCrossplaneConstraints: false
  package: {{ .image }}
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  {{- if .deploymentRuntimeConfig }}
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: {{ .deploymentRuntimeConfig.name }}
  {{- end }}
  skipDependencyResolution: false
  {{- if .deploymentRuntimeConfig }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: {{ .deploymentRuntimeConfig.name }}
spec:
  deploymentTemplate:
    spec:
      replicas: 1
      selector: {}
      template:
        spec:
          serviceAccountName: {{ .name }}-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .name }}-cr
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .name }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .name }}-cr
subjects:
  - kind: ServiceAccount
    name: {{ .name }}-sa
    namespace: default                        
  {{- end }}
{{ end }}