{{ range .Values.providers }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ .name }}
spec:
  ignoreCrossplaneConstraints: false
  package: {{ .image }}
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  {{- if .deploymentRuntimeConfig }}
  runtimeConfigRef:
    apiVersion: {{ .deploymentRuntimeConfig.apiVersion }}
    kind: DeploymentRuntimeConfig
    name: {{ .deploymentRuntimeConfig.name }}
  {{- end }}  
  skipDependencyResolution: false
  {{- if .deploymentRuntimeConfig }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: {{ .deploymentRuntimeConfig.name }}
spec:
  deploymentTemplate:
    spec:
      replicas: 1
      selector: {}
      template:
        spec:
            serviceAccountName: {{ .name }}-sa
  {{- end }}
{{ end }}