name: Deploy Helm Chart

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Optional: Trigger the workflow on pull requests to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.0'  # Specify the Helm version you want to use

    - name: Install k3d
      run: |
        curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash

    - name: Create k3d cluster
      run: k3d cluster create mycluster

    - name: Configure kubectl
      run: |
        k3d kubeconfig get mycluster > $HOME/.kube/config
        export KUBECONFIG=$HOME/.kube/config

    - name: Configure Kubernetes
      uses: azure/k8s-set-context@v3
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}  # Use the kubeconfig stored in GitHub secrets

    - name: Deploy Helm Chart
      run: |
        helm template my-release ./providers-functions \
          --namespace my-namespace