name: Deploy Helm Chart

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Optional: Trigger the workflow on pull requests to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.0'  # Specify the Helm version you want to use

    - name: Install k3d
      run: |
        curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash

    - name: Create k3d cluster without Traefik
      run: k3d cluster create mycluster --k3s-arg "--disable=traefik@server:0"

    - name: Helm lint
      run: helm lint ./

    - name: Install Helm unittest plugin
      run: helm plugin install https://github.com/quintush/helm-unittest

    - name: Run Helm unit tests
      run: helm unittest ./

    - name: Install Crossplane
      run: |
        kubectl create namespace crossplane-system
        helm repo add crossplane-stable https://charts.crossplane.io/stable
        helm repo update
        helm install crossplane --namespace crossplane-system crossplane-stable/crossplane

    - name: Wait for Crossplane to be ready
      run: |
        kubectl wait --for=condition=available --timeout=600s deployment/crossplane --namespace crossplane-system

    - name: Render Helm templates and dry run with kubectl
      run: helm template . -g | kubectl apply -f - --dry-run=server

    - name: Delete k3d cluster
      run: k3d cluster delete mycluster