name: Test Helm Chart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Lint Helm chart
      run: helm lint ./providers-functions

    - name: Install Helm chart
      run: helm install my-release ./providers-functions --dry-run

    - name: Test Helm chart
      run: helm test my-release
