name: Test Helm Chart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Install k3d
      run: |
        curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash

    - name: Create k3d cluster
      run: k3d cluster create mycluster

    - name: Initialize Helm
      run: helm repo add stable https://charts.helm.sh/stable

    - name: Install Crossplane
      run: |
        kubectl create namespace crossplane-system
        helm init --wait
        helm repo add crossplane-stable https://charts.crossplane.io/stable
        helm repo update
        helm install crossplane --namespace crossplane-system crossplane-stable/crossplane

    - name: Lint Helm chart
      run: helm lint ./providers-functions

    - name: Install Helm chart
      run: helm install my-release ./providers-functions --dry-run

    - name: Test Helm chart
      run: helm test my-release
